-- Recurring expense enhancements:
-- 1. auto_post: false = expense recorded only when user confirms payment
--               true  = auto-generated by scheduler on due date (default, backwards-compat)
-- 2. reminder_days: array of days-before-due to send email reminders
-- 3. Automation settings: recurring reminder config

ALTER TABLE recurring_expense_templates
  ADD COLUMN IF NOT EXISTS auto_post      BOOLEAN   NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS reminder_days  INTEGER[] NOT NULL DEFAULT '{30,7}';

ALTER TABLE automation_settings
  ADD COLUMN IF NOT EXISTS recur_reminder_enabled  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS recur_reminder_email    TEXT,
  ADD COLUMN IF NOT EXISTS recur_reminder_last_run TIMESTAMPTZ;
